export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED';

export const REQUEST_ROBOTS_POSTS = 'REQUEST_ROBOTS_POSTS';
export const REQUEST_ROBOTS_POSTS_SUCCESS = 'REQUEST_ROBOTS_POSTS_SUCCESS';
export const REQUEST_ROBOTS_POSTS_FAILED = 'REQUEST_ROBOTS_POSTS_FAILED';